apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: transactions
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          # - shard: "shadow"
          #   cluster: https://kubernetes.default.svc        
          - shard: "01"
            cluster: https://kubernetes.default.svc
          - shard: "02"
            cluster: https://kubernetes.default.svc
          - shard: "03"
            cluster: https://kubernetes.default.svc
  strategy:
    type: RollingSync
    rollingSync:
      steps:
        - matchExpressions:
            - key: shard
              operator: In
              values:
                - "01"
        - matchExpressions:
            - key: shard
              operator: In
              values:
                - "02"
        - matchExpressions:
            - key: shard
              operator: In
              values:
                - "03"     
  template:
    metadata:
      name: transactions-{{ shard }}
      labels:
        shard: "{{ shard }}"
    spec:
      project: "transactions-shard-{{ shard }}"
      source:
        repoURL: 'http://chartmuseum.chartmuseum.svc.cluster.local:8080'
        chart: sample
        targetRevision: 0.1.0
        helm:
          releaseName: transactions-{{ shard }}
          valuesObject:
            app:
              name: transactions
              image: ghcr.io/msfidelis/msc-transactions-api:0.0.4
              namespace: shard-{{ shard }}
              iam: "none"
              capacity:
                requests:
                  cpu: 100m
                  memory: 128Mi
                limits: 
                  cpu: 200m
                  memory: 256Mi
                autoscaling: {}
                min: 2
                max: 10
              rollout:
                strategy:
                  canary:
                    steps:
                    - setWeight: 0
                    - pause: { duration: 30s }
                    - setWeight: 100
              envs:
                - name: DATABASE_HOST
                  value: "db-{{ shard }}-postgresql"
                - name: DATABASE_PORT
                  value: "5432"
                - name: DATABASE_USER
                  value: "fidelissauro"
                - name: DATABASE_PASSWORD
                  value: "doutorequemtemdoutorado"
                - name: DATABASE_DB
                  value: "transactions"
                - name: CACHE_HOST
                  value: "redis-{{ shard }}-master"
                - name: CACHE_PORT
                  value: "6379"
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: POD_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
              port:
                name: http-web
                port: 8080
                protocol: TCP
                targetPort: 8080
              service:
                type: ClusterIP
              
              # Configurações de DNS e rede
              dnsPolicy: ClusterFirst
              dnsConfig:
                options:
                  - name: ndots
                    value: "1"
                  - name: timeout
                    value: "5"
                  - name: attempts
                    value: "3"
              
              istio:
                gateway: 
                  selector: ingressgateway
                  # HTTP, HTTP2, GRPC, GRPC-WEB, MONGO, REDIS, MYSQL, TCP
                  protocol: HTTP 
                  port: 80
                host: transactions{{ shard }}.cluster.io
                virtualService:
                  http:
                    enabled: true
                    retries:
                      attempts: 2
                      perTryTimeout: 2s
                      retryOn: connect-failure,refused-stream,unavailable,cancelled,503
                DestinationRule:
                  enabled: true

              prometheus:
                scrape: "true"
                port: 8080
                path: /metrics

              probes:
                readinessProbe:
                  enabled: true
                  initialDelaySeconds: 30
                  periodSeconds: 10
                  timeoutSeconds: 5
                  failureThreshold: 3
                  httpGet:
                    path: /healthcheck
                    port: 8080
                livenessProbe:
                  enabled: true
                  initialDelaySeconds: 60
                  failureThreshold: 10
                  periodSeconds: 10
                  timeoutSeconds: 5
                  httpGet:
                    path: /healthcheck
                    port: 8080
                startupProbe:
                  enabled: true
                  initialDelaySeconds: 30
                  failureThreshold: 30
                  periodSeconds: 10
                  timeoutSeconds: 5
                  httpGet:
                    path: /healthcheck
                    port: 8080

      destination:
        server: '{{ cluster }}'
        namespace: argocd
      # syncPolicy:
        # automated: {}