mode: deployment

image:
  repository: otel/opentelemetry-collector-k8s
  pullPolicy: IfNotPresent

config:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
        http:
          endpoint: 0.0.0.0:4318
    zipkin: {}

  processors:
    batch: {}

  exporters:
    otlphttp:
      endpoint: "http://tempo-gateway.tempo.svc.cluster.local:80"
      tls:
        insecure: true

  service:
    pipelines:
      traces:
        receivers: [otlp, zipkin]
        processors: [batch]
        exporters: [otlphttp]