# alertmanager:
#   persistentVolume:
#     enabled: false
#   replicas: 1
#   resources:
#     limits:
#       memory: 1.4Gi
#     # requests:
#     #   cpu: 1
#     #   memory: 1Gi
#   statefulSet:
#     enabled: false

# compactor:
#   persistentVolume:
#     size: 20Gi
#   resources:
#     limits:
#       memory: 2.1Gi
#     # requests:
#     #   cpu: 1
#     #   memory: 1.5Gi

# distributor:
#   replicas: 2
#   resources:
#     limits:
#       memory: 5.7Gi
#     # requests:
#     #   cpu: 2
#     #   memory: 4Gi

# ingester:
#   persistentVolume:
#     size: 50Gi
#   replicas: 3
#   resources:
#     limits:
#       memory: 12Gi
#     # requests:
#     #   cpu: 3.5
#     #   memory: 8Gi

# admin-cache:
#   enabled: true
#   replicas: 1

# chunks-cache:
#   enabled: true
#   replicas: 1

# index-cache:
#   enabled: true
#   replicas: 1

# metadata-cache:
#   enabled: true
#   replicas: 1

# results-cache:
#   enabled: true
#   replicas: 1

# minio:
#   enabled: false

# overrides_exporter:
#   replicas: 1
#   resources:
#     limits:
#       memory: 128Mi
#     requests:
#       cpu: 100m
#       memory: 128Mi

# querier:
#   replicas: 1
#   resources:
#     limits:
#       memory: 5.6Gi
#     # requests:
#     #   cpu: 2
#     #   memory: 4Gi

# query_frontend:
#   replicas: 1
#   resources:
#     limits:
#       memory: 2.8Gi
#     # requests:
#     #   cpu: 2
#     #   memory: 2Gi

# ruler:
#   replicas: 1
#   resources:
#     limits:
#       memory: 2.8Gi
#     # requests:
#     #   cpu: 1
#     #   memory: 2Gi

# store_gateway:
#   persistentVolume:
#     size: 10Gi
#   replicas: 1
#   resources:
#     limits:
#       memory: 2.1Gi
#     # requests:
#     #   cpu: 1
#     #   memory: 1.5Gi

# nginx:
#   replicas: 1
#   resources:
#     limits:
#       memory: 731Mi
#     requests:
#       cpu: 1
#       memory: 512Mi

# # Grafana Enterprise Metrics feature related
# admin_api:
#   replicas: 1
#   resources:
#     limits:
#       memory: 128Mi
#     # requests:
#     #   cpu: 100m
#     #   memory: 64Mi

# gateway:
#   replicas: 1
#   resources:
#     limits:
#       memory: 731Mi
#     # requests:
#     #   cpu: 1
#     #   memory: 512Mi