apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: prometheus
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - cluster: https://kubernetes.default.svc
  template:
    metadata:
      name: prometheus
    spec:
      project: "system"
      source:
        repoURL: 'https://prometheus-community.github.io/helm-charts'
        chart: prometheus
        targetRevision: 27.11.0
        helm:
          releaseName: prometheus
          valuesObject:

            prometheusSpec:

              enableRemoteWriteReceiver: true
              enableFeatures:
              - remote-write-receiver

              podMonitorNamespaceSelector: {}
              podMonitorSelector: {}
              podMonitorSelectorNilUsesHelmValues: false
              ruleNamespaceSelector: {}
              ruleSelector: {}
              ruleSelectorNilUsesHelmValues: false
              serviceMonitorNamespaceSelector: {}
              serviceMonitorSelector: {}
              serviceMonitorSelectorNilUsesHelmValues: false


            server:
              global:
                scrape_interval: 15s
                evaluation_interval: 15s
                external_labels:
                    cluster: "{{ cluster }}"
              persistentVolume:
                enabled: true
              extraFlags:
                - 'web.enable-remote-write-receiver'

              # remoteWrite:
              #   - url: "http://mimir.linuxtips-observability.local:80/api/v1/push"
              #     queue_config:
              #       max_samples_per_send: 1000
              #       max_shards: 20
              #       capacity: 5000

              prometheus-node-exporter:
                enabled: true
              alertmanager:
                enabled: false

              extraScrapeConfigs: |
                - job_name: "envoy-stats-monitor"
                  honor_labels: true
                  scrape_interval: 15s
                  kubernetes_sd_configs:
                    - role: pod
                  relabel_configs:
                    - action: drop
                      source_labels: [__meta_kubernetes_pod_label_istio_prometheus_ignore]
                      regex: .+
                    - action: keep
                      source_labels: [__meta_kubernetes_pod_container_name]
                      regex: "istio-proxy"
                    - action: keep
                      source_labels: [__meta_kubernetes_pod_annotationpresent_prometheus_io_scrape]
                      regex: "true"
                    - action: replace
                      source_labels:
                        - __meta_kubernetes_pod_annotation_prometheus_io_port
                        - __meta_kubernetes_pod_ip
                      regex: (\d+);(([A-Fa-f0-9]{1,4}::?){1,7}[A-Fa-f0-9]{1,4})
                      replacement: '[$2]:$1'
                      target_label: __address__
                    - action: replace
                      source_labels:
                        - __meta_kubernetes_pod_annotation_prometheus_io_port
                        - __meta_kubernetes_pod_ip
                      regex: (\d+);((([0-9]+?)(\.|$)){4})
                      replacement: $2:$1
                      target_label: __address__
                    - action: labeldrop
                      regex: "__meta_kubernetes_pod_label_(.+)"
                    - action: replace
                      source_labels: [__meta_kubernetes_namespace]
                      target_label: namespace
                    - action: replace
                      source_labels: [__meta_kubernetes_pod_name]
                      target_label: pod_name
                  metrics_path: /stats/prometheus
      destination:
        server: '{{ cluster }}'
        namespace: prometheus
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
        automated: {}