apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: prometheus-crds
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - cluster: https://kubernetes.default.svc
  template:
    metadata:
      name: prometheus-crds
    spec:
      project: "system"
      source:
        repoURL: 'https://prometheus-community.github.io/helm-charts'
        chart: prometheus-operator-crds
        targetRevision: 20.0.1
        helm:
          releaseName: prometheus-crds
          valuesObject:

            prometheusSpec:

      destination:
        server: '{{ cluster }}'
        namespace: prometheus
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
        automated: {}