# apiVersion: networking.istio.io/v1alpha3
# kind: Gateway
# metadata:
#   name: argocd-gateway
#   namespace: argocd
# spec:
#   selector:
#     istio: ingressgateway 
#   servers:
#   - port:
#       number: 80
#       name: http
#       protocol: HTTP
#     hosts:
#     - argocd.homelab.msfidelis.com.br
# ---
# apiVersion: networking.istio.io/v1alpha3
# kind: VirtualService
# metadata:
#   name: argo-server
#   namespace: argocd
# spec:
#   hosts:
#   - argocd.homelab.msfidelis.com.br
#   gateways:
#   - argocd-gateway
#   http:
#   - match:
#     - uri:
#         prefix: /
#     route:
#     - destination:
#         host: argocd-server
#         port:
#           number: 80