# apiVersion: networking.istio.io/v1alpha3
# kind: Gateway
# metadata:
#   name: jaeger-query
#   namespace: tracing
# spec:
#   selector:
#     istio: ingressgateway 
#   servers:
#   - port:
#       number: 80
#       name: http
#       protocol: HTTP
#     hosts:
#     - jaeger.homelab.msfidelis.com.br
# ---
# apiVersion: networking.istio.io/v1alpha3
# kind: VirtualService
# metadata:
#   name: jaeger-query
#   namespace: tracing
# spec:
#   hosts:
#   - jaeger.homelab.msfidelis.com.br
#   gateways:
#   - jaeger-query
#   http:
#   - route:
#     - destination:
#         host: jaeger-query
#         port:
#           number: 16686 