apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: fluent-bit
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - cluster: https://kubernetes.default.svc
  template:
    metadata:
      name: fluent-bit
    spec:
      project: "system"
      source:
        repoURL: "https://fluent.github.io/helm-charts"
        chart: fluent-bit
        targetRevision: 0.48.10
        helm:
          releaseName: fluent-bit
          valuesObject:
                    
            serviceAccount:
              create: true
              name: fluent-bit

            config:
              service: |
                [SERVICE]
                    HTTP_Server  On
                    HTTP_Listen  0.0.0.0
                    HTTP_PORT    2020
                    Flush        1
                    Log_Level    info
                    Parsers_File parsers.conf

              inputs: |
                [INPUT]
                    Name              tail
                    Path              /var/log/containers/*.log
                    Parser            cri
                    Tag               kube.*
                    Mem_Buf_Limit     50MB
                    Skip_Long_Lines   On
                    Refresh_Interval  10

              filters: |
                [FILTER]
                    Name                kubernetes
                    Match               kube.*
                    Kube_URL            https://kubernetes.default.svc:443
                    Merge_Log           On
                    K8S-Logging.Parser  On
                    K8S-Logging.Exclude Off

              outputs: |
                [OUTPUT]
                    Name              loki
                    Match             kube.*
                    Host              loki-gateway.loki.svc.cluster.local
                    Port              80
                    tls               off
                    tls.verify        off
                    line_format       json
                    Labels            cluster=homelab,job=fluentbit,namespace=$kubernetes['namespace_name'],pod=$kubernetes['pod_name'],container=$kubernetes['container_name']



      destination:
        server: '{{ cluster }}'
        namespace: fluent-bit
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated: {}