apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cert-manager
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - cluster: https://kubernetes.default.svc
  template:
    metadata:
      name: cert-manager
    spec:
      project: "system"
      source:
        repoURL: "https://charts.jetstack.io"
        chart: "cert-manager"
        targetRevision: "v1.19.2"
        helm:
          releaseName: "cert-manager"
          valuesObject:
            crds:
              enabled: true
      destination:
        server: "{{ cluster }}"
        namespace: cert-manager
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated: {}