apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kafka-ui
  namespace: argocd
spec:
  generators:
    - list:
        elements:     
          - shard: "01"
            cluster: https://kubernetes.default.svc    
  template:
    metadata:
      name: kafka-ui
      labels:
        shard: "{{ shard }}"
    spec:
      project: "ledger"
      source:
        repoURL: 'http://chartmuseum.chartmuseum.svc.cluster.local:8080'
        chart: sample
        targetRevision: 0.1.0
        helm:
          releaseName: kafka-ui
          valuesObject:
            app:
              name: kafka-ui
              image: provectuslabs/kafka-ui:latest
              namespace: ledger
              iam: "none"
              capacity:
                requests:
                  cpu: 100m
                  memory: 128Mi
                limits: 
                  cpu: 200m
                  memory: 256Mi
                autoscaling: {}
                min: 1
                max: 1
              rollout:
                strategy:
                  canary:
                    steps:
                    - setWeight: 100
              envs:
                # - name: KAFKA_CLUSTERS_0_NAME
                #   value: "local"
                - name: KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS
                  value: "ledger-kafka-controller-headless.ledger.svc.cluster.local:9092"
                - name: DYNAMIC_CONFIG_ENABLED
                  value: "true"

              port:
                name: http-web
                port: 8080
                protocol: TCP
                targetPort: 8080
              service:
                type: ClusterIP
              
              # Configurações de DNS e rede
              dnsPolicy: ClusterFirst
              dnsConfig:
                options:
                  - name: ndots
                    value: "1"
                  - name: timeout
                    value: "5"
                  - name: attempts
                    value: "3"
              
              istio:
                gateway: 
                  selector: ingressgateway
                  # HTTP, HTTP2, GRPC, GRPC-WEB, MONGO, REDIS, MYSQL, TCP
                  protocol: HTTP 
                  port: 80
                host: kafka-ui-ledger.homelab.fidelissauro.dev
                virtualService:
                  http:
                    enabled: true
                    retries:
                      attempts: 2
                      perTryTimeout: 2s
                      retryOn: connect-failure,refused-stream,unavailable,cancelled,503
                DestinationRule:
                  enabled: true

              prometheus:
                scrape: "false"
                port: 8080
                path: /metrics

              probes:
                readinessProbe:
                  enabled: false
                  initialDelaySeconds: 30
                  periodSeconds: 10
                  timeoutSeconds: 5
                  failureThreshold: 3
                  httpGet:
                    path: /actuator/health
                    port: 8080
                livenessProbe:
                  enabled: false
                  initialDelaySeconds: 60
                  failureThreshold: 10
                  periodSeconds: 10
                  timeoutSeconds: 5
                  httpGet:
                    path: /actuator/health
                    port: 8090
                startupProbe:
                  enabled: false
                  initialDelaySeconds: 30
                  failureThreshold: 30
                  periodSeconds: 10
                  timeoutSeconds: 5
                  httpGet:
                    path: /actuator/health
                    port: 8090

      destination:
        server: '{{ cluster }}'
        namespace: argocd
      syncPolicy:
        automated: {}